### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by malte-hansen**
- ~~Fix reference to TeeTime Repository~~
- Remove edge crossings in flow chart

### CODE REVIEW

**Review by shinhyungyang — APPROVED** [review]
Thank you for the fix!
@DaGeRe Could you have a look and merge?

**Comment by DaGeRe** [comment]
Thanks for the PR, very nice that you were able to remove the edge crossing. For the TeeTime repo, as fas as I know, it should be inside of the kieker-monitoring organization, since we'll need to transfer it there (the teetime-framework organization is no longer maintained, and we want to have access management etc. centralized in the kieker-monitoring organization).

**Comment by malte-hansen** [comment]
I see, what do you propose then? Leave that part of the README unchanged?

**Comment by DaGeRe** [comment]
Yes, that would be the easiest solution. I justed forked the main TeeTime repo into the kieker-monitoring organization, so the link works now.

**Comment by malte-hansen** [comment]
Done. I updated the pull request such that only the edge crossing in the graph are removed.

**Comment by DaGeRe** [comment]
Thanks, looks good!

**Pull request merged**
